name: Build iOS (Unsigned IPA, No Cert)

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repo
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          git init
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com//iamCristYE/lucky-scan.git
          git fetch
          git checkout origin/main

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "FLUTTER_ROOT=$HOME/flutter" >> $GITHUB_ENV

      - name: Flutter doctor (quick sanity check)
        run: flutter doctor -v

      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Debug Generated.xcconfig
        run: |
          if [ -f ios/Flutter/Generated.xcconfig ]; then
            echo "Generated.xcconfig exists"
            grep "FLUTTER_ROOT" ios/Flutter/Generated.xcconfig
          else
            echo "Generated.xcconfig NOT found"
          fi


      - name: Set timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Precache iOS artifacts
        run: flutter precache --ios

      # Build the iOS app bundle
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      # Manually package the .app into an unsigned .ipa
      - name: Package unsigned IPA
        run: |
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r luckyscan.ipa Payload
          cd ../../..

      - name: Upload Artifact (unsigned IPA)
        uses: actions/upload-artifact@v6
        with:
          name: luckyscan-ios-release-${{ env.TIMESTAMP }}
          path: build/ios/iphoneos/luckyscan.ipa
          if-no-files-found: error


