name: Build Mock Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          git init
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com//iamCristYE/lucky-scan.git
          git fetch
          git checkout origin/main

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone Flutter repository with stable channel
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: flutter pub get

      - name: Set timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
          echo "TIMESTAMP_INT=$(date +'%s' | cut -c 1-9)" >> $GITHUB_ENV

      - name: Build Mock Debug APK
        run: |
          flutter build apk --debug \
            --dart-define=MOCK_API=true \
            --build-name="1.0.${{ env.TIMESTAMP }}-mock" \
            --build-number=${{ env.TIMESTAMP_INT }}

      - name: Prepare artifacts
        run: |
          mv build/app/outputs/flutter-apk/app-debug.apk luckyscan_mock_${{ env.TIMESTAMP }}.apk

      - name: Upload Mock APK
        uses: actions/upload-artifact@v6
        with:
          name: luckyscan-mock-debug-${{ env.TIMESTAMP }}
          path: |
            luckyscan_mock_${{ env.TIMESTAMP }}.apk
